### ISSUE TITLE
Building on 32bit chroot on 64bit host produces objects in /usr/lib64

### ISSUE THREAD

**Issue by slackhead** [TimothyGu/libilbc#19]
While building in a 32bit chroot on a 64bit host the shared object is installed in /usr/lib64 instead of /usr/lib.

I don't see any cmake option to specify libdir.

This line seems to be doing it:

```cmake
get_property(LIB64 GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS)
```

I can get around it by sedding the CMakeLists.txt for now, but wonder if there's a better way?

**Comment by slackhead** [comment]
I should add that this is also the case when building in a 32 OS where the CPU is 64bit.

**Comment by TimothyGu** [comment]
So… you are using CMake? I'm asking as there are literally 3 supported build systems.

**Comment by slackhead** [comment]
Yes.. but autotools seems to work better. I noticed the cmake files but not the configure. Thanks for the headsup and sorry for the noise. Closing.

**Comment by TimothyGu** [comment]
@slackhead Uh, they are not autotools, but a hacked-up version of FFmpeg's configure script. But good to hear it's working.

**Comment by TimothyGu** [comment]
Oops that's a different project I maintain. sorry about the noise.

**Comment by TimothyGu** [comment]
I think the issue itself still stands. My gut tells me that it's your CMake setup's problem.
