### ISSUE TITLE
[Request] PGP-sign tags and tarball sources

### ISSUE THREAD

**Issue by dbermond** [TimothyGu/libilbc#30]
Thank you for PGP-signing the release commits, as this increases security.

Could you please also PGP-sign the tags? This will make it easier for packaging.

PGP-signing the tarball sources will be good too :)

**Comment by TimothyGu** [comment]
Interesting, I didn’t realize tag signing is controlled by a different flag from commit signing. I’ll do that soon.

**Comment by TimothyGu** [comment]
Signed the newest release (v3.0.2). PGP signatures added for both [3.0.2](https://github.com/TimothyGu/libilbc/releases/tag/v3.0.2) and [3.0.1](https://github.com/TimothyGu/libilbc/releases/tag/v3.0.1).

**Comment by dbermond** [comment]
Thanks! This improves packaging :)
