### ISSUE TITLE
Missing symbol from the shared library

### ISSUE THREAD

**Issue by dbermond** [TimothyGu/libilbc#32]
The symbol `WebRtcIlbcfix_InitDecode` is missed from the shared library. The following command produces no output:

```
$ nm -D libilbc.so | grep 'WebRtcIlbcfix_InitDecode'
```

As a result, applications that uses this function and tries to link against `libilbc.so` fails to build. For example, FFmpeg is showing me this error:

```
/usr/bin/ld: /tmp/ffconf.mxjpOf0E/test.o: in function `check_WebRtcIlbcfix_InitDecode':
test.c:(.text+0x3): undefined reference to `WebRtcIlbcfix_InitDecode'
collect2: error: ld returned 1 exit status
ERROR: libilbc not found
```

This can be fixed by the following modification, but I'm not sure if it would be desirable for the project. Probably there could be a better solution.

```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -44,7 +44,6 @@ if(NOT CMAKE_BUILD_TYPE)
     set(CMAKE_BUILD_TYPE Release)
 endif()
 
-set(CMAKE_C_VISIBILITY_PRESET hidden)
 set(CMAKE_CXX_VISIBILITY_PRESET hidden)
 set(CMAKE_VISIBILITY_INLINES_HIDDEN 1)
 
```

**Comment by TimothyGu** [comment]
Darn, I fixed this for [init\_encode](https://github.com/TimothyGu/libilbc/blob/08e7b85564118d14af4a810026615029f35e6c48/modules/audio_coding/codecs/ilbc/init_encode.c#L19) but not init\_decode…

**Comment by dbermond** [comment]
Thank you for fixing this! Working fine now :)
